import type { VercelRequest, VercelResponse } from './_types';
import { createClient } from '@supabase/supabase-js';
const json=(res:VercelResponse,status:number,body:unknown)=>res.status(status).json(body);
const admin=()=>createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
export default async function handler(req:VercelRequest,res:VercelResponse){
 if(req.method!=='POST')return json(res,405,{message:'Method not allowed'});
 if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY||!process.env.MIDTRANS_SERVER_KEY)return json(res,500,{message:'Payment gateway backend belum dikonfigurasi.'});
 try{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();if(!token)return json(res,401,{message:'Session token diperlukan.'});const sb=admin();const {data:u,error:ae}=await sb.auth.getUser(token);if(ae||!u.user)return json(res,401,{message:'Session tidak valid.'});const {data:p,error:pe}=await sb.from('profiles').select('organization_id').eq('id',u.user.id).maybeSingle();if(pe||!p?.organization_id)return json(res,403,{message:'Organisasi pengguna tidak ditemukan.'});
 const body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});const invoiceId=String(body.invoiceId||'');if(!invoiceId)return json(res,400,{message:'invoiceId wajib diisi.'});
 const {data:i,error:ie}=await sb.from('invoices').select('id,organization_id,invoice_number,customer_id,grand_total,paid_amount,outstanding_amount,status').eq('id',invoiceId).eq('organization_id',p.organization_id).maybeSingle();if(ie||!i)return json(res,404,{message:'Invoice tidak ditemukan.'});const amount=Number(i.outstanding_amount);if(!Number.isFinite(amount)||amount<=0)return json(res,409,{message:'Invoice tidak memiliki sisa tagihan.'});
 const {data:existing}=await sb.from('payment_gateway_transactions').select('*').eq('organization_id',p.organization_id).eq('invoice_id',i.id).in('status',['PENDING','ACTIVE']).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(existing?.payment_url)return json(res,200,{paymentUrl:existing.payment_url,transactionId:existing.id,orderId:existing.order_id,expiresAt:existing.expires_at,status:existing.status});
 const production=String(process.env.MIDTRANS_ENV||'sandbox').toLowerCase()==='production';const base=production?'https://app.midtrans.com':'https://app.sandbox.midtrans.com';const api=production?'https://api.midtrans.com':'https://api.sandbox.midtrans.com';const orderId=`BF-${i.invoice_number.replace(/[^A-Za-z0-9]/g,'-')}-${Date.now()}`.slice(0,48);const expiry=Number(process.env.MIDTRANS_EXPIRY_MINUTES||1440);const expiresAt=new Date(Date.now()+expiry*60000).toISOString();const auth=Buffer.from(`${process.env.MIDTRANS_SERVER_KEY}:`).toString('base64');
 const {data:c}=await sb.from('customers').select('name,company_name,email,phone').eq('id',i.customer_id).eq('organization_id',p.organization_id).maybeSingle();const gr=await fetch(`${api}/snap/v1/transactions`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({transaction_details:{order_id:orderId,gross_amount:Math.round(amount)},credit_card:{secure:true},expiry:{unit:'minutes',duration:expiry},customer_details:{first_name:c?.company_name||c?.name||'Customer',email:c?.email||undefined,phone:c?.phone||undefined},item_details:[{id:i.id,price:Math.round(amount),quantity:1,name:`Pembayaran ${i.invoice_number}`} ]})});const g=await gr.json().catch(()=>({}));if(!gr.ok||!g.token)return json(res,502,{message:g?.status_message||'Midtrans gagal membuat transaksi.'});const paymentUrl=`${base}/snap/v4/redirection/${g.token}`;
 const {data:s,error:se}=await sb.from('payment_gateway_transactions').insert({organization_id:p.organization_id,invoice_id:i.id,provider:'midtrans',order_id:orderId,transaction_id:null,amount,currency:'IDR',payment_url:paymentUrl,token:g.token,status:'PENDING',expires_at:expiresAt,metadata:g}).select().single();if(se)return json(res,500,{message:se.message});return json(res,200,{paymentUrl,transactionId:s.id,orderId,expiresAt,status:'PENDING'});
 }catch(e:any){console.error(e);return json(res,500,{message:e?.message||'Internal server error.'})}}
